name: vprofile-app workflow
on:
 push:
jobs:
  vprofile-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the vprofile code
        uses: actions/checkout@v1
      - name: Build artifacts
        run: | 
          mvn install
          mv target/vprofile-v2.war .
          rm -rf target
          mkdir target
          mv vprofile-v2.war target/
          ls -l target
         
